"""add user model provider settings

Revision ID: 0537f90d9fc7
Revises: 1b3d96b80d10
Create Date: 2026-03-10 13:48:42.316227

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0537f90d9fc7"
down_revision: Union[str, Sequence[str], None] = "1b3d96b80d10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_model_provider_settings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("provider_id", sa.String(length=64), nullable=False),
        sa.Column("model_ids", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "provider_id",
            name="uq_user_model_provider_settings_user_provider",
        ),
    )
    op.create_index(
        op.f("ix_user_model_provider_settings_user_id"),
        "user_model_provider_settings",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_model_provider_settings_user_id"),
        table_name="user_model_provider_settings",
    )
    op.drop_table("user_model_provider_settings")
    # ### end Alembic commands ###
