"""create preset visuals table

Revision ID: 06407b1d392d
Revises: b8868c7ab79f
Create Date: 2026-04-04 14:17:50.326348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06407b1d392d'
down_revision: Union[str, Sequence[str], None] = 'b8868c7ab79f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preset_visuals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('hash', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=512), nullable=False),
    sa.Column('managed_by', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_preset_visual_key')
    )
    op.create_index(op.f('ix_preset_visuals_key'), 'preset_visuals', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preset_visuals_key'), table_name='preset_visuals')
    op.drop_table('preset_visuals')
    # ### end Alembic commands ###
