"""empty message

Revision ID: 0f0033af79a0
Revises: 51643c2207d3
Create Date: 2026-01-27 15:38:50.260354

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0f0033af79a0"
down_revision: Union[str, Sequence[str], None] = "51643c2207d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skill_import_jobs",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("archive_key", sa.Text(), nullable=False),
        sa.Column("selections", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_skill_import_jobs_status"),
        "skill_import_jobs",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_skill_import_jobs_user_id"),
        "skill_import_jobs",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_skill_import_jobs_user_id"), table_name="skill_import_jobs")
    op.drop_index(op.f("ix_skill_import_jobs_status"), table_name="skill_import_jobs")
    op.drop_table("skill_import_jobs")
    # ### end Alembic commands ###
