"""empty message

Revision ID: a5582f015bfd
Revises: 331320b4f8d1
Create Date: 2026-02-28 20:34:16.151861

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a5582f015bfd"
down_revision: Union[str, Sequence[str], None] = "331320b4f8d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_agent_messages_session_id"),
        "agent_messages",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        "ix_agent_messages_session_id_created_at_id",
        "agent_messages",
        ["session_id", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_agent_runs_session_id_status",
        "agent_runs",
        ["session_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_agent_runs_status_scheduled_at_created_at",
        "agent_runs",
        ["status", "scheduled_at", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_sessions_sdk_session_id"),
        "agent_sessions",
        ["sdk_session_id"],
        unique=False,
    )
    op.create_index(
        "ix_agent_sessions_sdk_session_id_is_deleted",
        "agent_sessions",
        ["sdk_session_id", "is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_sessions_user_id"), "agent_sessions", ["user_id"], unique=False
    )
    op.create_index(
        "ix_agent_sessions_user_id_is_deleted_created_at",
        "agent_sessions",
        ["user_id", "is_deleted", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tool_executions_session_id"),
        "tool_executions",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        "ix_tool_executions_session_id_created_at_id",
        "tool_executions",
        ["session_id", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_user_input_requests_session_id_status_created_at",
        "user_input_requests",
        ["session_id", "status", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_user_input_requests_session_id_status_created_at",
        table_name="user_input_requests",
    )
    op.drop_index(
        "ix_tool_executions_session_id_created_at_id", table_name="tool_executions"
    )
    op.drop_index(op.f("ix_tool_executions_session_id"), table_name="tool_executions")
    op.drop_index(
        "ix_agent_sessions_user_id_is_deleted_created_at", table_name="agent_sessions"
    )
    op.drop_index(op.f("ix_agent_sessions_user_id"), table_name="agent_sessions")
    op.drop_index(
        "ix_agent_sessions_sdk_session_id_is_deleted", table_name="agent_sessions"
    )
    op.drop_index(op.f("ix_agent_sessions_sdk_session_id"), table_name="agent_sessions")
    op.drop_index(
        "ix_agent_runs_status_scheduled_at_created_at", table_name="agent_runs"
    )
    op.drop_index("ix_agent_runs_session_id_status", table_name="agent_runs")
    op.drop_index(
        "ix_agent_messages_session_id_created_at_id", table_name="agent_messages"
    )
    op.drop_index(op.f("ix_agent_messages_session_id"), table_name="agent_messages")
    # ### end Alembic commands ###
