"""add description to skills table

Revision ID: ac35ccd45c9d
Revises: 74e90ae3d7a1
Create Date: 2026-03-12 13:30:51.323371

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ac35ccd45c9d"
down_revision: Union[str, Sequence[str], None] = "98b9968cc9be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "skills", sa.Column("description", sa.String(length=1000), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("skills", "description")
    # ### end Alembic commands ###
