"""add description to projects

Revision ID: adbcc3fc76a9
Revises: b97f576b621d
Create Date: 2026-03-31 22:39:19.830598

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "adbcc3fc76a9"
down_revision: Union[str, Sequence[str], None] = "b97f576b621d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "description")
    # ### end Alembic commands ###
