"""add project runtime config

Revision ID: c7900166fbca
Revises: 833daf707b32
Create Date: 2026-04-01 19:04:30.848957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7900166fbca'
down_revision: Union[str, Sequence[str], None] = '833daf707b32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('default_model', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('mount_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('projects', sa.Column('mount_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'mount_path')
    op.drop_column('projects', 'mount_enabled')
    op.drop_column('projects', 'default_model')
    # ### end Alembic commands ###
