"""add embedded im tables

Revision ID: d4019c5265dc
Revises: 9a4fff9b8b57
Create Date: 2026-03-15 22:14:22.614668

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d4019c5265dc"
down_revision: Union[str, Sequence[str], None] = "9a4fff9b8b57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channels",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("destination", sa.String(length=255), nullable=False),
        sa.Column(
            "enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "subscribe_all",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "destination", name="uq_channel"),
    )
    op.create_index(
        op.f("ix_channels_destination"), "channels", ["destination"], unique=False
    )
    op.create_index(
        op.f("ix_channels_provider"), "channels", ["provider"], unique=False
    )
    op.create_table(
        "dedup_events",
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "active_sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_id", name="uq_active_session_channel"),
    )
    op.create_index(
        op.f("ix_active_sessions_channel_id"),
        "active_sessions",
        ["channel_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_active_sessions_session_id"),
        "active_sessions",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "channel_deliveries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("send_address", sa.String(length=2048), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("channel_id", name="uq_channel_delivery_channel_id"),
    )
    op.create_index(
        op.f("ix_channel_deliveries_channel_id"),
        "channel_deliveries",
        ["channel_id"],
        unique=False,
    )
    op.create_table(
        "watched_sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["channel_id"], ["channels.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "channel_id", "session_id", name="uq_watch_channel_session"
        ),
    )
    op.create_index(
        op.f("ix_watched_sessions_channel_id"),
        "watched_sessions",
        ["channel_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_watched_sessions_session_id"),
        "watched_sessions",
        ["session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_watched_sessions_session_id"), table_name="watched_sessions")
    op.drop_index(op.f("ix_watched_sessions_channel_id"), table_name="watched_sessions")
    op.drop_table("watched_sessions")
    op.drop_index(
        op.f("ix_channel_deliveries_channel_id"), table_name="channel_deliveries"
    )
    op.drop_table("channel_deliveries")
    op.drop_index(op.f("ix_active_sessions_session_id"), table_name="active_sessions")
    op.drop_index(op.f("ix_active_sessions_channel_id"), table_name="active_sessions")
    op.drop_table("active_sessions")
    op.drop_table("dedup_events")
    op.drop_index(op.f("ix_channels_provider"), table_name="channels")
    op.drop_index(op.f("ix_channels_destination"), table_name="channels")
    op.drop_table("channels")
    # ### end Alembic commands ###
