"use client";

import type { LucideIcon } from "lucide-react";
import {
  BarChart3,
  Bot,
  BookOpen,
  Braces,
  Bug,
  ClipboardList,
  Cloud,
  Cpu,
  Code2,
  Database,
  FileText,
  FolderOpen,
  GitBranch,
  Globe,
  Image,
  Link,
  Mail,
  MessageSquare,
  Paintbrush2,
  PenLine,
  Rocket,
  Search,
  Shield,
  Sparkles,
  Target,
  Terminal,
  Wrench,
  Zap,
} from "lucide-react";

import type { PresetIcon } from "@/features/capabilities/presets/lib/preset-types";

export const PRESET_ICON_ORDER: PresetIcon[] = [
  "default",
  "code",
  "branch",
  "database",
  "globe",
  "paintbrush",
  "book",
  "chip",
  "robot",
  "file",
  "message",
  "chart",
  "shield",
  "terminal",
  "zap",
  "pen",
  "wrench",
  "link",
  "cpu",
  "search",
  "mail",
  "image",
  "folder",
  "clipboard",
  "bug",
  "cloud",
  "rocket",
  "target",
];

export const PRESET_ICON_MAP: Record<PresetIcon, LucideIcon> = {
  default: Sparkles,
  code: Code2,
  branch: GitBranch,
  database: Database,
  globe: Globe,
  paintbrush: Paintbrush2,
  book: BookOpen,
  chip: Braces,
  robot: Bot,
  file: FileText,
  message: MessageSquare,
  chart: BarChart3,
  shield: Shield,
  terminal: Terminal,
  zap: Zap,
  pen: PenLine,
  wrench: Wrench,
  link: Link,
  cpu: Cpu,
  search: Search,
  mail: Mail,
  image: Image,
  folder: FolderOpen,
  clipboard: ClipboardList,
  bug: Bug,
  cloud: Cloud,
  rocket: Rocket,
  target: Target,
};

export const PRESET_COLOR_OPTIONS = [
  "#f97316",
  "#ef4444",
  "#eab308",
  "#22c55e",
  "#14b8a6",
  "#0ea5e9",
  "#3b82f6",
  "#8b5cf6",
  "#ec4899",
  "#6b7280",
] as const;

export function getPresetIcon(icon: PresetIcon): LucideIcon {
  return PRESET_ICON_MAP[icon] ?? Sparkles;
}
